version: '2.2'

services:
  master:
    build: ./docker/master/
    hostname: salt-master
    volumes:
      - ./data/master.conf:/etc/salt/master.d/master.conf
      - ./data/pillar:/srv/pillar
      - ./data/salt:/srv/salt
      - ./data/formulas:/srv/formulas
  minion-prod:
    build: ./docker/minion/
    environment:
      - SALT_PREFIX=prod
    depends_on:
      - master
    volumes:
      - ./data/minion.conf:/etc/salt/minion.d/minion.conf
    scale: 2
  minion-dev:
    build: ./docker/minion/
    environment:
      - SALT_PREFIX=dev
    depends_on:
      - master
    volumes:
      - ./data/minion.conf:/etc/salt/minion.d/minion.conf
    scale: 2